version: '3'

services:
  lavagna-app:
    build: .
    environment:
      - DB_DIALECT=MYSQL
      - DB_URL=jdbc:mysql://mysql:3306/lavagna?autoReconnect=true&useSSL=false
      - DB_USER=root
      - DB_PASS=root_pass
      - SPRING_PROFILE=prod
    volumes:
    - my-webapp:/app/target/lavagna
    depends_on:
      - mysql
    networks:
      - fronend-network
      - backend-network

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: lavagna
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - backend-network

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 8081:8081
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - my-webapp:/usr/share/nginx/webapp
    depends_on:
      - lavagna-app
    networks:
      - fronend-network

networks:
  fronend-network:
    driver: bridge
  backend-network:
    driver: bridge
volumes:
  mysql-db:
  my-webapp:
